database:
  db1:
    databaseName: prueba
    host: localhost
    port: 3306
    username: root
    password: root

  db2:
    databaseName: tmandty
    host: localhost
    port: 5433
    username: sportilla
    password: root

  dbparasumerce:
    databaseName: TMandTY
    host: localhost
    port: 5432
    username: suuser
    password: supassword